Lesson 36
K-Maxim/todolist_app pull request #1
Opened 2022-10-26 19:08 UTC by K-Maxim

2022-10-26 20:51 UTC, painassasin requested changes

2022-10-26 20:51 UTC, painassasin commented on goals/tests.py
> +from django.test import TestCase
Кажется этот файл лишний и его можно удалить)

2022-10-26 20:51 UTC, painassasin commented on goals/views.py
> +        instance.save()
При удалении категории, всем связанным с ней целям нужно поставить статус archived, причем лучше это сделать атомарно:
```python
with transaction.atomic():
    ...
 ```

2022-10-26 20:51 UTC, painassasin commented on todolist/settings.py
> +import django_filters.rest_framework
Для чего этот импорт?

2022-10-27 10:58 UTC, K-Maxim commented on goals/tests.py
> +from django.test import TestCase
Удалил

2022-10-27 11:17 UTC, K-Maxim commented on todolist/settings.py
> +import django_filters.rest_framework
Я его не писал, могу предположить, что он сам подтянулся (вот только не знаю каким образом)

2022-10-27 19:37 UTC, painassasin approved these changes

2022-10-31 19:14 UTC, merged