Diploma
K-Maxim/todolist_app pull request #4
Opened 2022-11-15 20:18 UTC by K-Maxim

2022-11-17 09:02 UTC, painassasin requested changes

2022-11-17 09:02 UTC, painassasin commented on goals/models.py
> +        Board, verbose_name="Доска", on_delete=models.PROTECT, related_name="categories", default=None
Как можно создать категорию без доски? Точнее вопрос, зачем `default=None`?

2022-11-17 09:02 UTC, painassasin commented on goals/permissions.py
>  class BoardPermissions(permissions.BasePermission):
В таком случае нужно унаследоваться от `IsAuthenticated`

2022-11-17 09:02 UTC, painassasin commented on goals/serializer.py
> +        instance.title = validated_data['title']
Сейчас у тебя на изменение доски обязательно нужно указывать `title`, но нужно дать возможность изменить только участников, чтобы поле `title` не было указано в запросе. В таком случае данный код не пройдет. Нужно поправить + тест.

2022-11-17 09:02 UTC, painassasin commented on goals/views.py
> +    ordering = ['title', ]
Напиши тест на данный кейс (создай несколько целей, например goal_2, goal_1, goal_3  и убедись, что на выходе будет корректная сортировка)  , что-то мне кажется она работать не будет

2022-11-17 09:02 UTC, painassasin commented on goals/views.py
> +    permission_classes = [IsAuthenticated, GoalPermissions]
Должно работать без IsAuthenticated

2022-11-17 15:10 UTC, K-Maxim commented on goals/views.py
> +    permission_classes = [IsAuthenticated, GoalPermissions]
Да, работает и без.

2022-11-17 15:12 UTC, K-Maxim commented on goals/models.py
> +        Board, verbose_name="Доска", on_delete=models.PROTECT, related_name="categories", default=None
Незачем, в этом нет смысла. Удалил.

2022-11-17 15:15 UTC, K-Maxim commented on goals/permissions.py
>  class BoardPermissions(permissions.BasePermission):
Унаследовал. Значит в пермишенах мы всегда наследуемся от IsAuthenticated?

2022-11-17 15:22 UTC, K-Maxim commented on goals/serializer.py
> +        instance.title = validated_data['title']
Подправил этот участок кода

2022-11-18 06:10 UTC, painassasin approved these changes

2022-11-18 06:11 UTC, painassasin approved these changes

2022-11-29 17:27 UTC, merged